language: go
go:
- '1.5'
install:
- go get -t -v ./...
- go test -v ./...
- go build -o bin/ccTray2Slack -v .
deploy:
  provider: releases
  clean_up: false
  skip_cleanup: true
  file: bin/ccTray2Slack
  api_key:
    secure: b+Sn0PrDmd8vm0zQP9umq+r1tW4MkOyz0W5UtLJP+ygXUvQZTxzt8+uZo6hYp6f3zD+Ps62TSIOwLD/3x5X324SzOGXKdgAKcNV+QlsRNPFShyQ0ayR4GGgfsD2exVOD360Ycn87m+OfTsXtOEtz8SxZv6E1XSlqs63jWdsjpBB0UG9n+dVL/RFGMu/U/6kUAxRcH1Dop6ssplJl/qxGCVLkQXuy2FRaCSvTqX/NHmjxI0K/GU6ydJ6Igjwv08Osclwo8unWQjUVbPNkXu3VqmG/cyTHbs+IByu2nYkMbvQYrD+WmHvfT/RVkS2yUlUtwrsVY72LnkkE44gtedgaHzfTeGiec4/wqxyO/Vur3Q7glccRQgTyZN8btnjn9eiQd1cIobBYjArVEUufOPaXfoNLIqVBofxBSDV7pSeDa+Cb6mtGh4S17If1osZSs7LdaxFY8dgwapokyx1AYXowRl0sIrlFR5wLZiS5J0XnDS+6ZsqZHbFXa0/Bad4zpadb+w3z/SggPq8csNlnLmXODudcr4KnFPdckglqnqE3BJSukGWaKPCpDvi0VJ+4xcnenxl3ejcL6psdW8BlXRnrwTBcJMWhdz9/8xhWMMQ/7eUpcInAXgGa35n2aURQrAamQhKhGQdkXbVMlQxLU8A2nxbbUkoVUWtI6NivKGftPnE=
  on:
    tags: true
    repo: christer79/ccTray2Slack
